#' A forest plot
#'
#' @param object An object generated by the meta function
#' @param study_names A character vector containing the names of each study
#' @param interval Credibility intervals for the summary (default=0.9)
#' @param xlab The name of the x-axis in the forest plot
#'
#' @description A forest plot that indicates all priors used in the model, all estimates included and the posterior distribution of the pooled
#' estimate.
#'
#' @export
forest <- function(object, study_names=NULL, interval=0.9, xlab="Estimate"){

  #study names
  if(is.null(study_names) || length(object$model$Data$est) != length(study_names)){
    study_names <- paste("study", 1:length(object$model$Data$est))}

  #Create table for all effect-sizes
  effdf <- setNames(cbind(as.character(object$model$Data$level), do.call(rbind.data.frame, strsplit(as.character(object$model$Data$level), "_")), study_names, object$model$Data$est,
                          object$model$Data$se), c("code", "parameter", "predictor", "link", "group", "study", "mu", "se"))

  #Calculate z-value for intervals
  z        <- qnorm(interval/2+0.5)

  #Calculate interval levels
  effdf$ll <- as.numeric(effdf$mu)-as.numeric(effdf$se)*z
  effdf$ul <- as.numeric(effdf$mu)+as.numeric(effdf$se)*z

  #split dataset
  split_df <- split(effdf, effdf$code)

  #create posterior mcmc objects
  post_df  <- split(object$Chains_mu, paste(object$Chains_mu$parameter,object$Chains_mu$predictor,
                                            object$Chains_mu$link, object$Chains_mu$group, sep="_"))

  #get the bayesfactors
  if(ncol(object$model$Priors)>3){bf_df <- round(get_BF(object)[[1]][,2],2)}

  #Create all plots
  plots <- lapply(1:length(split_df), function(x){

    pl2 <- ggplot(split_df[[x]], aes(as.numeric(mu), study))+
      geom_point()+geom_vline(xintercept = 0, lty=2, lwd=0.6, col="tomato3")+
      geom_errorbarh(data=split_df[[x]], aes(xmin=ll, xmax=ul), height=0)+
      theme_classic()+
      theme(axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            axis.line = element_blank(),
            axis.ticks = element_blank(),
            axis.text.x = element_blank(),
            legend.position = "none")

    #get xlims from forest plot
    xlims <- ggplot_build(pl2)$layout$panel_params[[1]]$x.range

    #generate lines to display priors
    prior_df  <- object$model$Priors[x,-1]
    mu_seq    <- seq(1, ncol(prior_df)/2, 1)
    se_seq    <- seq((ncol(prior_df)/2+1), ncol(prior_df), 1)
    x_seq     <- seq(xlims[1], xlims[2] , length.out = 300)

    #scale priors to equal height
    scaled_prior <- lapply(1:(ncol(prior_df)/2), function(i) {
      y <- dnorm(x_seq, as.numeric(prior_df[mu_seq[i]]), as.numeric(prior_df[se_seq[i]]))
      data.frame(p=i, x = x_seq, y = y / max(y))})

    #generate prior df
    prior_df     <- do.call(rbind.data.frame, scaled_prior)

    #plot priors
    pl3 <- ggplot(prior_df, aes(x, y, group=p, col=as.factor(p)))+
      geom_line()+labs(col="Prior")+scale_color_grey(start = 0.85, end = 0.15)+
      geom_vline(xintercept = 0, lty=2, lwd=0.6, col="tomato3")+
      theme_classic()+
      theme(axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            axis.line = element_blank(),
            axis.ticks = element_blank(),
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            legend.position = "top")

    if(ncol(object$model$Priors[x,-1])>3){
      text <- paste0(c("mu=", "se=", "\nll=", "ul=", "I2=", "\nBF="), c(round(object$Summary[x,c("mu", "se", "ll", "ul", "I2")],2),bf_df[x]), collapse = ", ")}else{
        text <- paste0(c("mu=", "se=", "\nll=", "ul=", "I2="), c(round(object$Summary[x,c("mu", "se", "ll", "ul", "I2")],2)), collapse = ", ")}

    post_bar <- object$Summary[x,c("ll", "ul")]
    if(post_bar$ll<xlims[1]){post_bar$ll <- xlims[1]}
    if(post_bar$ul>xlims[2]){post_bar$ul <- xlims[2]}

    pl1 <- ggplot(post_df[[x]], aes(estimate, group=group))+
      xlim(c(xlims[1], xlims[2]))+
      geom_point(data=object$Summary[x,], aes(x=mu, y=0), inherit.aes = F)+
      geom_errorbarh(data=post_bar, aes(xmin=ll, xmax=ul, y=0), height=0, inherit.aes = F)+
      geom_vline(xintercept = 0, lty=2, lwd=0.6, col="tomato3")+
      geom_density()+xlab(xlab)+
      theme_classic()+
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            axis.line.y = element_blank(),
            axis.ticks.y = element_blank(),
            legend.position = "none")

    ylims <- ggplot_build(pl1)$layout$panel_params[[1]]$y.range[2]/1.5

    pl1 <- pl1+annotate("text", x =  ifelse(sign(xlims[1])==-1,xlims[1]+diff(xlims)*0.1,xlims[1]-diff(xlims)*0.1),
                        y = ylims, label = text, size = 2.5)

    cowplot::plot_grid(pl3, pl2, pl1, ncol=1, rel_heights = c(0.25, 0.55, 0.2), align = "v")

  })

  return(list(figures=plots, data=split_df))}
