#' A forest plot
#'
#' @param object An object generated by the meta function
#' @param study_names A character vector containing the names of each study
#' @param interval Credibility intervals for the summary (default=0.9)
#' @param rel_height Relative heights of the three sub-figures in the plot
#' @param label_x_pos Position of the label along x-axis within the posterior plot
#' @param label_y_pos Position of the label along y-axis within the posterior plot
#' @param xlimit xlimit The limits of the x-axis
#' @param xlab The name of the x-axis in the forest plot
#' @param label_size The text size of the label
#'
#' @description A forest plot that indicates all priors used in the model, all estimates included and the posterior distribution of the pooled
#' estimate.
#'
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 scale_color_grey
#' @importFrom stats quantile
#'
#' @export
forestplot <- function(object, study_names=NULL, interval=0.9,
                       rel_heights = c(0.25, 0.55, 0.2),
                       label_x_pos=NULL, label_y_pos=NULL,
                       xlimit=NULL, xlab="Estimate", label_size=3){

  #study names
  if(is.null(study_names) || length(object$model$Data$est) != length(study_names)){
    study_names <- 1:length(object$model$Data$est)
    add_names   <- 0}else{add_names <- 1}

  #Create table for all effect-sizes
  effdf <- setNames(cbind(as.character(object$model$Data$level), do.call(rbind.data.frame, strsplit(as.character(object$model$Data$level), "_")), study_names, object$model$Data$est,
                          object$model$Data$se), c("code", "parameter", "predictor", "link", "group", "study", "mu", "se"))

  #Calculate z-value for intervals
  z        <- qnorm(interval/2+0.5)

  #Calculate interval levels
  effdf$ll <- as.numeric(effdf$mu)-as.numeric(effdf$se)*z
  effdf$ul <- as.numeric(effdf$mu)+as.numeric(effdf$se)*z

  #split dataset
  split_df <- split(effdf, effdf$code)

  #create posterior mcmc objects
  post_df  <- split(object$Chains_mu, paste(object$Chains_mu$parameter,object$Chains_mu$predictor,
                                            object$Chains_mu$link, object$Chains_mu$group, sep="_"))

  #select only b1
  sel_b1 <- which(do.call(rbind.data.frame, lapply(split_df, function(df) unique(df[, 2])))[,1] == "b1")

  post_df     <- post_df[sel_b1]
  split_df    <- split_df[sel_b1]
  split_prior <- object$model$Priors[sel_b1,]

  #get the bayesfactors
  if(ncol(split_prior)>3){bf_df <- round(get_BF(object)[[1]][,2],2)}

  #if names is NULL
  if(add_names == 0){
    addn <- element_blank()
  }else{
    addn <- element_text()
  }

  #x-axis limits
  if(is.null(xlimit)){
    xlim_pl2 <- NULL
  }else{
    xlim_pl2 <- xlim(xlimit[1], xlimit[2])
  }


  #Create all plots
  plots <- lapply(1:length(split_df), function(x){

    if(!is.null(xlimit)){
      split_df[[x]]$ll[split_df[[x]]$ll< xlimit[1]] <- xlimit[1]
      split_df[[x]]$ul[split_df[[x]]$ul> xlimit[2]] <- xlimit[2]}

    pl2 <- ggplot(split_df[[x]], aes(as.numeric(mu), study))+
      geom_point()+geom_vline(xintercept = 0, lty=2, lwd=0.6, col="tomato3")+
      geom_errorbarh(data=split_df[[x]], aes(xmin=ll, xmax=ul), width=0)+
      theme_classic()+
      xlim_pl2+
      theme(axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            axis.line = element_blank(),
            axis.ticks = element_blank(),
            axis.text.y = addn,
            axis.text.x = element_blank(),
            legend.position = "none")

    #get xlims from forest plot
    xlims <- ggplot_build(pl2)$layout$panel_params[[1]]$x.range

    #generate lines to display priors
    prior_df  <- split_prior[x,-1]
    mu_seq    <- seq(1, ncol(prior_df)/2, 1)
    se_seq    <- seq((ncol(prior_df)/2+1), ncol(prior_df), 1)
    x_seq     <- seq(xlims[1], xlims[2] , length.out = 300)

    #scale priors to equal height
    scaled_prior <- lapply(1:(ncol(prior_df)/2), function(i) {
      y <- dnorm(x_seq, as.numeric(prior_df[mu_seq[i]]), as.numeric(prior_df[se_seq[i]]))
      data.frame(p=i, x = x_seq, y = y / max(y))})

    #generate prior df
    prior_df     <- do.call(rbind.data.frame, scaled_prior)

    #if only two priors set to H1 H0
    if (length(unique(prior_df$p)) == 2) {
      map <- c(`1` = "H1", `2` = "H0")
      p_chr <- as.character(prior_df$p)
      idx <- p_chr %in% names(map)
      p_chr[idx] <- map[p_chr[idx]]
      prior_df$p <- p_chr
      prior_df$p <- factor(prior_df$p, levels = c("H1", "H0"))
    }else{
      p_chr <- as.character(prior_df$p)
      nums <- sort(unique(p_chr))
      map <- setNames(paste0("Mod", nums), nums)
      prior_df$p <- map[p_chr]
    }

    #plot priors
    pl3 <- ggplot(prior_df, aes(x, y, group=p, col=as.factor(p)))+
      geom_line()+labs(col="Prior")+ggplot2::scale_color_grey(start = 0.85, end = 0.15)+
      geom_vline(xintercept = 0, lty=2, lwd=0.6, col="tomato3")+
      theme_classic()+
      theme(axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            axis.line = element_blank(),
            axis.ticks = element_blank(),
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            legend.position = "top")

    if (ncol(object$model$Priors[x, -1]) > 3) {
      text <- paste0(
        "mu=", round(object$Summary[x,"mu"], 2), " ",
        "se=", round(object$Summary[x,"se"], 2), "\n",
        "ll=", round(object$Summary[x,"ll"], 2), " ",
        "ul=", round(object$Summary[x,"ul"], 2), " ",
        "I2=", round(object$Summary[x,"I2"], 2), "\n",
        "BF=", bf_df[x]
      )} else {
      text <- paste0(
        "mu=", round(object$Summary[x,"mu"], 2), " ",
        "se=", round(object$Summary[x,"se"], 2), "\n",
        "ll=", round(object$Summary[x,"ll"], 2), " ",
        "ul=", round(object$Summary[x,"ul"], 2), " ",
        "I2=", round(object$Summary[x,"I2"], 2)*100,"%")}

    post_bar <- object$Summary[x,c("ll", "ul")]
    if(post_bar$ll<xlims[1]){post_bar$ll <- xlims[1]}
    if(post_bar$ul>xlims[2]){post_bar$ul <- xlims[2]}

    pl1 <- ggplot(post_df[[x]], aes(estimate, group=group))+
      xlim(c(xlims[1], xlims[2]))+
      geom_point(data=object$Summary[x,], aes(x=mu, y=0), inherit.aes = F)+
      geom_errorbarh(data=post_bar, aes(xmin=ll, xmax=ul, y=0), width=0, inherit.aes = F)+
      geom_vline(xintercept = 0, lty=2, lwd=0.6, col="tomato3")+
      geom_density()+xlab(xlab)+
      theme_classic()+
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            axis.line.y = element_blank(),
            axis.ticks.y = element_blank(),
            legend.position = "none")

    if(is.null(label_y_pos)){ylim_lab <- ggplot_build(pl1)$layout$panel_params[[1]]$y.range[2]/1.5
      }else{ylim_lab <- ggplot_build(pl1)$layout$panel_params[[1]]$y.range[2]*label_y_pos}

    if(is.null(label_x_pos)){xlim_lab <- ifelse(sign(xlims[1])==-1,xlims[1]+diff(xlims)*0.1,xlims[1]-diff(xlims)*0.1)
      }else{xlim_lab <-  label_x_pos}

    pl1 <- pl1+annotate("text", x = xlim_lab,
                        y = ylim_lab, label = text,
                        size = label_size)

    cowplot::plot_grid(pl3, pl2, pl1, ncol=1, rel_heights = rel_heights, align = "v")

  })

  return(list(figures=plots, data=split_df))}

