#' Title
#'
#' @param object An object generated by the mar function
#' @param interval What interval to display
#' @param display Which model parameter to display b1 or b0 (currently only b1)
#' @param order_predictor The order of the predictors
#' @param order_group The order of the groups
#' @param top_label The space for the top label
#' @param left_label The space for the left labels
#' @param title_size Size of the titles
#' @param label_size Size of the labels in the plots
#' @param line_width The line width
#' @param point_size The size of the point
#' @param err_bar_lwd The line width of the error bars
#' @param xlab The x-label text
#' @param ylab The y-label text
#' @param xylab_size x and y label size
#' @param xtext_size size of the x-axis text
#'
pdplot <- function(object, interval=0.9, display="b1",
                   order_predictor = NULL, order_group = NULL,
                   top_label=0.05, left_label=0.1,
                   title_size=3, label_size=1.6,
                   line_width=0.2, point_size=.5, err_bar_lwd=0.2,
                   xlab="Parameter estimate",
                   ylab="Posterior density",
                   xylab_size=3, xtext_size=8){

#Extract b1 or b0
if(display=="b1"){object1   <- object$Estimates$b1}else{stop("b0 not yet implemented")}

#Sample size
df_n                        <- setNames(as.data.frame(object$N_level), c("code", "n"))
df_n$code                   <- as.character(df_n$code)

#set interval
interval_level              <- 0.5+c(-1,1)*interval/2

#Split the mcmc chains per group predictor and link
split_mcmc       <- split(object1$estimate, paste(object1$group, object1$predictor, object1$link, sep="_"))

#unique combinations
names_mcmc  <- expand.grid(unique(object1$group), unique(object1$predictor), unique(object1$link))
names_mcmc  <- setNames(cbind(names_mcmc, apply(names_mcmc, 1, paste, collapse = "_")), c("group", "predictor", "link", "code"))
names_mcmc  <- merge(names_mcmc, df_n, by="code", all.x = T)

#count groups and predictors
n_group <- length(unique(names_mcmc$group))
n_pred  <- length(unique(names_mcmc$predictor))

#order per group and predictor
if(!is.null(order_group)&&!is.null(order_group)){
  names_mcmc$group     <- factor(names_mcmc$group, levels = order_group)
  names_mcmc$predictor <- factor(names_mcmc$predictor, levels = order_predictor)
  names_mcmc           <- names_mcmc[order(names_mcmc$group, names_mcmc$predictor),]
  split_mcmc           <- split_mcmc[c(names_mcmc$code)]
}else if(!is.null(order_group)&&is.null(order_predictor)){
  names_mcmc$group     <- factor(names_mcmc$group, levels = order_group)
  names_mcmc$predictor <- factor(names_mcmc$predictor, levels = levels(names_mcmc$predictor))
  names_mcmc           <- names_mcmc[order(names_mcmc$group),]
  split_mcmc           <- split_mcmc[c(names_mcmc$code)]
}else if(!is.null(order_predictor)&&is.null(order_group)){
  names_mcmc$group     <- factor(names_mcmc$group, levels = levels(names_mcmc$group))
  names_mcmc$predictor <- factor(names_mcmc$predictor, levels = order_predictor)
  names_mcmc           <- names_mcmc[order(names_mcmc$predictor),]
  split_mcmc           <- split_mcmc[c(names_mcmc$code)]
}else{
  names_mcmc$group     <- factor(names_mcmc$group, levels = levels(names_mcmc$group))
  names_mcmc$predictor <- factor(names_mcmc$predictor, levels = levels(names_mcmc$predictor))
  names_mcmc           <- names_mcmc[order(names_mcmc$group, names_mcmc$predictor),]
  split_mcmc           <- split_mcmc[c(names_mcmc$code)]}

#create a list to store figures
plot_list              <- list()
est_df                 <- setNames(as.data.frame(array(NA, dim=c(nrow(names_mcmc), 6))), c("map", "mu", "se", "ll", "ul", "x"))

for(i in 1:length(split_mcmc)){

  if(is.null(split_mcmc[[i]])){plot_list[[names_mcmc$code[i]]]<- ggplot()+theme_void()}else{

maxpost <- function(x){d <- density(x); d$x[which.max(d$y)]}

est_df[i,]              <- c(maxpost(split_mcmc[[i]]), mean(split_mcmc[[i]]),
                             sd(split_mcmc[[i]]), quantile(split_mcmc[[i]], interval_level[1]),
                             quantile(split_mcmc[[i]], interval_level[2]), x=0)

if(max(abs(range(split_mcmc[[i]])))>1){
      xbreaks <- scale_x_continuous(breaks = seq(-2,2,1))
}else{xbreaks <- scale_x_continuous(breaks = seq(-1.5,1.5,.5))}

pl <- ggplot(data.frame(x=split_mcmc[[i]]), aes(x=x))+
    geom_density(alpha=0.2, lwd=line_width)+
    geom_point(data=est_df[i,], aes(x=as.numeric(map), y=0), inherit.aes = F, size=point_size)+
    geom_errorbarh(data=est_df[i,], aes(xmin=as.numeric(ll), xmax=as.numeric(ul),y=0),
                   height=0, lwd=err_bar_lwd)+
    geom_vline(xintercept = 0, lty=2, lwd=line_width, col="black")+
    xbreaks+
    theme_classic()+
    theme(axis.title = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_text(size = xtext_size),
          line = element_line(linewidth = line_width),
          plot.margin = unit(c(.1, .1, .1, .1), "mm"))

xrange_pl<- ggplot_build(pl)$layout$panel_scales_x[[1]]$range$range
yrange_pl<- ggplot_build(pl)$layout$panel_scales_y[[1]]$range$range

if(sign(est_df[i,]$map)==1){
  x_loc <- xrange_pl[1]+diff(xrange_pl)/4}else{
    x_loc <- xrange_pl[2]-diff(xrange_pl)/4}

y_loc <- yrange_pl[2]-diff(yrange_pl)/5

lab_pl <- paste0("map=", round(est_df[i,]$map,2),"\nse=", round(est_df[i,]$se,2))
pl     <- pl+annotate("text", x=x_loc, y_loc, label=lab_pl, size=label_size)

plot_list[[names_mcmc$code[i]]] <- pl
}}

#separate the figures per link function
linkfunction     <- unique(names_mcmc$link)
link_list        <- vector("list", length(linkfunction))
names(link_list) <- linkfunction

for(i in linkfunction){
  do.call(rbind, strsplit(names(plot_list), "_"))[,3]
link_list[[i]] <- plot_list[names_mcmc$link == i]}

#create empty plots with group names
grn <- lapply(unique(names_mcmc$group), function(x) ggplot()+annotate("text", 0, 0, label=x, size=title_size, fontface = "bold")+theme_void())
groupnameplots <- cowplot::plot_grid(plotlist = grn, ncol=1)

#create empty plots with predictor names
prn <- vector("list", length(unique(names_mcmc$predictor))+1)
prn[2:length(prn)] <- lapply(unique(names_mcmc$predictor), function(x) ggplot()+annotate("text", 0, 0, label=x, size=title_size, fontface = "bold")+theme_void())
prednameplots <- cowplot::plot_grid(plotlist = prn, nrow=1)

#create x and y title
xtitle <- ggplot()+annotate("text", 0, 0, label=xlab, size=xylab_size)+theme_void()
ytitle <- ggplot()+annotate("text", 0, 0, label=ylab, size=xylab_size, angle = 90)+theme_void()

#create all density plots
dens_list <- list()
for(i in names(link_list)){
densplots <- cowplot::plot_grid(plotlist = link_list[[i]], nrow = n_group, ncol = n_pred)

pl1 <- cowplot::plot_grid(groupnameplots, densplots, rel_widths = c(left_label, 1-left_label))
pl2 <- cowplot::plot_grid(prednameplots, pl1, xtitle, rel_heights = c(top_label, 1-(top_label+0.03), 0.03), ncol = 1)
dens_list[[i]] <- cowplot::plot_grid(pl2, ytitle, rel_widths = c(0.9, 0.03))}

return(list(posterior_density=dens_list, summary=est_df[,-ncol(est_df)]))}
