---
title: "EcoPostView: Ecological Posterior View"
author: Willem (Wim) Kaijser
output: 
  bookdown::gitbook:
    toc_depth: 4
    number_sections: true
    highlight: tango
---
<style>
.main-container {
  max-width: 100%;
}

body {
  text-align: justify;
}

.outline-block {
  border: 2px solid #333;
  padding: 1em;
  margin: 1em 0;
  border-radius: 6px;
  background-color: #fafafa;
}
</style>

```{r setup_1, include = FALSE}
library(EcoPostView)

#unlink("C:/Users/admin/AppData/Local/R/win-library/4.3/_build/00LOCK-EcoPostView", recursive = TRUE, force = TRUE)
#
#unlink("C:/Users/admin/OneDrive/Bureaublad/EcoPostView.Rcheck", recursive = TRUE, force = TRUE)
#
#dir.exists("C:/Users/admin/AppData/Local/R/win-library/4.3/_build/00LOCK-EcoPostView")
#dir.exists("C:/Users/admin/OneDrive/Bureaublad/EcoPostView.Rcheck")

#check stuff
#devtools::check(check_dir = "C:/temp/EcoPostView-check")
#
#build book
#devtools::document()
#devtools::install(upgrade = "never")
#
#create the book
#setwd("C:/Users/admin/OneDrive/Bureaublad/EcoPostView/book")
#bookdown::render_book("index.Rmd")

```

# Overview

This is a working site with multiple projects, each chapter serves as a project although connected. It serves as a way to organize my thoughts and collect fragments of information. The project originally started including philosophical basis, but I have omitted this. Each chapter contains a project or miscellaneous functions and ideas/thoughts and some heterodox-statistical theory at the end.

The after the first 
Chapter (1.) *Introduction* is just a general introduction. 
Chapter (2.) focuses *Meta-analysis over effect-sizes and model parameters* focuses on how to do a more broad scale meta-analysis, with possibility to included moderators, random effects, test hypothesis, check for bias and correct for bias. This chapter is connected to the publication of Kaijser et al. (2025)
Chapter (3.) Introduces the method/framework of the *Posterior Predictive Meta-Analytic Network*. As for chapter (2.) It aims at synthesizing model parameters. However, it specifically aims at creating a network of this that can provide predictions, update its structure, and assess how information flows through the network. I hope to publish an article to this method soon.

On the left, you will find these chapters in the drop down menu. This site is still a work in progress — a kind of evolving rather than a polished presentation. 


